/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Authentication:": {                             "en": "Authentication:",                                 "de": "Authentifikation:",                               "ru": "Аутентификация:",                                 "pt": "Autenticação:",                                   "nl": "authenticatie:",                                  "fr": "Authentification:",                               "it": "Autenticazione:",                                 "es": "Autenticación:",                                  "pl": "Poświadczenie:",                                  "zh-cn": "验证："},
    "Chained certificate:": {                        "en": "Chained certificate:",                            "de": "Kettenzertifikat:",                               "ru": "'Chained' сертификат:",                           "pt": "Certificado acorrentado:",                        "nl": "Geketend certificaat:",                           "fr": "Certificat chaîné:",                              "it": "Certificato incatenato:",                         "es": "Certificado encadenado:",                         "pl": "Przykuty certyfikat:",                            "zh-cn": "链式证书："},
    "Force Web-Sockets:": {                          "en": "Force Web-Sockets:",                              "de": "Nur Web-Sockets:",                                "ru": "Только Web-Sockets:",                             "pt": "Forçar Sockets Web:",                             "nl": "Force Web-Sockets:",                              "fr": "Forcer les Web-Sockets:",                         "it": "Force Web-Sockets:",                              "es": "Force Web-Sockets:",                              "pl": "Wymuszaj Web-Sockets:",                           "zh-cn": "强制Web套接字："},
    "IP:": {                                         "en": "IP:",                                             "de": "IP:",                                             "ru": "IP:",                                             "pt": "IP:",                                             "nl": "IK P:",                                           "fr": "IP:",                                             "it": "IP:",                                             "es": "IP:",                                             "pl": "IP:",                                             "zh-cn": "IP："},
    "Let's Encrypt settings": {                      "en": "Let's Encrypt settings",                          "de": "Einstellungen Let's Encrypt",                     "ru": "Настройки Let's Encrypt",                         "pt": "Vamos criptografar configurações",                "nl": "Laten we de instellingen versleutelen",           "fr": "Encryptons les paramètres",                       "it": "Let's Encrypt settings",                          "es": "Vamos a cifrar la configuración",                 "pl": "Zaszyfruj ustawienia",                            "zh-cn": "我们加密设置"},
    "Port:": {                                       "en": "Port:",                                           "de": "Port:",                                           "ru": "Порт:",                                           "pt": "Porta:",                                          "nl": "Haven:",                                          "fr": "Port:",                                           "it": "Porta:",                                          "es": "Puerto:",                                         "pl": "Port:",                                           "zh-cn": "港口："},
    "Private certificate:": {                        "en": "Private certificate:",                            "de": "Privatzertifikat:",                               "ru": "'Private' сертификат:",                           "pt": "Certificado particular:",                         "nl": "Privé certificaat:",                              "fr": "Certificat privé:",                               "it": "Certificato privato:",                            "es": "Certificado privado:",                            "pl": "Prywatny certyfikat:",                            "zh-cn": "私人证书："},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "on save adapter startet sofort mit der neuen config neu", "ru": "при сохранении адаптер перезапускается с новым конфигом немедленно", "pt": "on save adapter reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur save, l'adaptateur redémarre immédiatement avec la nouvelle configuration", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en guardar adaptador se reinicia con nueva configuración inmediatamente", "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją", "zh-cn": "保存适配器立即重新启动新配置"},
    "Public certificate:": {                         "en": "Public certificate:",                             "de": "Publikzertifikat:",                               "ru": "'Public' сертификат:",                            "pt": "Certificado público:",                            "nl": "Openbaar certificaat:",                           "fr": "Certificat public:",                              "it": "Certificato pubblico:",                           "es": "Certificado público:",                            "pl": "Certyfikat publiczny:",                           "zh-cn": "公证书："},
    "Secure(HTTPS):": {                              "en": "Secure(HTTPS):",                                  "de": "Verschlüsselung(HTTPS):",                         "ru": "Шифрование(HTTPS):",                              "pt": "Seguro (HTTPS):",                                 "nl": "Secure (HTTPS):",                                 "fr": "Sécurisé (HTTPS):",                               "it": "Sicuro (HTTPS):",                                 "es": "Seguro (HTTPS):",                                 "pl": "Bezpieczne (HTTPS):",                             "zh-cn": "安全（HTTPS）："},
    "Set certificates or load it first in the system settings (right top).": {"en": "Set certificates or load it first in the system settings (right top).", "de": "Setze Zertificate oder lade die erst unter System/Einstellungen (oben rechts).", "ru": "Нужно выбрать сертификаты или сначала загрузить их в системных настройках (вверху справа).", "pt": "Defina certificados ou carregue-os primeiro nas configurações do sistema (parte superior direita).", "nl": "Stel certificaten in of laad het eerst in de systeeminstellingen (rechtsboven).", "fr": "Définissez les certificats ou chargez-le d'abord dans les paramètres système (en haut à droite).", "it": "Imposta i certificati o caricali prima nelle impostazioni di sistema (in alto a destra).", "es": "Configure los certificados o cárguelos primero en la configuración del sistema (arriba a la derecha).", "pl": "Ustaw certyfikaty lub załaduj najpierw w ustawieniach systemu (prawy górny).", "zh-cn": "设置证书或首先在系统设置中加载它（右上角）。"},
    "Terminal Server adapter settings": {            "en": "Terminal Server adapter settings",                "de": "Terminal Server adapter settings",                "ru": "Terminal Server adapter settings",                "pt": "Configurações do adaptador do Terminal Server",   "nl": "Terminal Server-adapterinstellingen",             "fr": "Paramètres de l'adaptateur Terminal Server",      "it": "Impostazioni dell'adattatore Terminal Server",    "es": "Configuración del adaptador de Terminal Server",  "pl": "Ustawienia adaptera serwera terminali",           "zh-cn": "终端服务器适配器设置"},
    "Use Lets Encrypt certificates:": {              "en": "Use Let's Encrypt certificates:",                 "de": "Benutzen Let's Encrypt Zertifikate:",             "ru": "Использовать сертификаты Let's Encrypt:",         "pt": "Use Vamos Criptografar Certificados:",            "nl": "Gebruik Let's Encrypt-certificaten:",             "fr": "Utilisez les certificats Let's Encrypt:",         "it": "Utilizza i certificati Let's Encrypt:",           "es": "Utilice certificados de Let's Encrypt:",          "pl": "Użyj Let's Encrypt certificates:",                "zh-cn": "使用Let的加密证书："},
    "socket_help": {                                 "en": "Used by adapters like rickshaw or vis",           "de": "Wird von Rickshaw oder Vis benutzt",              "ru": "Используется для Rickshaw или Vis",               "pt": "Usado por adaptadores como riquixá ou vis",       "nl": "Gebruikt door adapters zoals riksja of vis",      "fr": "Utilisé par des adaptateurs comme pousse-pousse ou vis", "it": "Usato da adattatori come risciò o vis",           "es": "Utilizado por adaptadores como rickshaw o vis",   "pl": "Używany przez adaptery takie jak riksza lub vis", "zh-cn": "由人力车或可见的适配器使用"},
};